=== mbta/schemas/schemas/com.mbta.ctd.glides.vehicle_trip_assignment.v1.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/mbta/schemas/blob/main/schemas/com.mbta.ctd.glides.vehicle_trip_assignment.v1.json",
  "description": "Vehicle Trip Assignment",
  "type": "object",
  "properties": {
    "type": { "const": "com.mbta.ctd.glides.vehicle_trip_assignment.v1" },
    "specversion": { "const": "1.0" },
    "source": { "$ref": "glides-events.json#/properties/source" },
    "id": { "$ref": "glides-events.json#/properties/id" },
    "time": { "$ref": "glides-events.json#/$defs/timestamp" },
    "data": {
      "type": "object",
      "properties": {
        "vehicleId": {
          "type": "string",
          "minLength": 1,
          "examples": ["G-10223"]
        },
        "tripKey": {
          "oneOf": [{ "$ref": "#/$defs/trip_key" }, { "const": null }]
        },
        "revenue": {
          "oneOf": [
            { "const": "revenue" },
            { "const": "nonrevenue" },
            { "const": null }
          ]
        }
      },
      "required": ["vehicleId", "tripKey"]
    }
  },
  "required": ["type", "specversion", "source", "id", "time", "data"],
  "$defs": {
    "trip_key": {
      "type": "object",
      "properties": {
        "serviceDate": {
          "$ref": "glides-events.json#/$defs/service_date"
        },
        "tripId": { "type": "string", "minLength": 1 },
        "scheduled": {
          "oneOf": [{ "const": "scheduled" }, { "const": "added" }]
        }
      },
      "required": ["serviceDate", "tripId", "scheduled"]
    }
  }
}

=== mbta/schemas/examples/glides-events/vehicle_trip_assignment.v1.json
[
  {
    "type": "com.mbta.ctd.glides.vehicle_trip_assignment.v1",
    "specversion": "1.0",
    "source": "glides.mbta.com",
    "id": "3442e845-ec46-4c39-a817-6444c7ce93d8",
    "time": "2024-11-14T09:50:00-05:00",
    "data": {
      "vehicleId": "G-12345",
      "tripKey": null,
      "revenue": null
    }
  },
  {
    "type": "com.mbta.ctd.glides.vehicle_trip_assignment.v1",
    "specversion": "1.0",
    "source": "glides.mbta.com",
    "id": "af639735-b8f1-416a-baa7-812d06a8fbcf",
    "time": "2024-11-14T10:00:00-05:00",
    "data": {
      "vehicleId": "G-12345",
      "tripKey": {
        "serviceDate": "2024-11-14",
        "tripId": "11111111",
        "scheduled": "scheduled"
      },
      "revenue": "revenue"
    }
  },
  {
    "type": "com.mbta.ctd.glides.vehicle_trip_assignment.v1",
    "specversion": "1.0",
    "source": "glides.mbta.com",
    "id": "9a708c96-3fdd-4a53-a2d7-a3f68bc9b7f5",
    "time": "2024-11-14T10:55:00-05:00",
    "data": {
      "vehicleId": "G-12345",
      "tripKey": {
        "serviceDate": "2024-11-14",
        "tripId": "22222222",
        "scheduled": "scheduled"
      },
      "revenue": "nonrevenue"
    }
  },
  {
    "type": "com.mbta.ctd.glides.vehicle_trip_assignment.v1",
    "specversion": "1.0",
    "source": "glides.mbta.com",
    "id": "16e65124-5b85-4522-bd93-9cacd6e57794",
    "time": "2024-11-14T11:55:00-05:00",
    "data": {
      "vehicleId": "G-12345",
      "tripKey": null,
      "revenue": null
    }
  }
]
