=== mbta/schemas/schemas/com.mbta.ocs.raw_message.json
{
  "$id": "https://github.com/mbta/schemas/blob/main/schemas/com.mbta.ocs.raw_message.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "description": "Raw message from the OCS",
  "type": "object",
  "properties": {
    "id": {
      "$ref": "cloudevents.json#/properties/id",
      "examples": ["prLSlfYXlQ8Nmsa8gyVi6PPZUmA="]
    },
    "source": {
      "$ref": "cloudevents.json#/properties/source",
      "examples": ["mbta.com/trike-12345"]
    },
    "specversion": {
      "const": "1.0",
      "$ref": "cloudevents.json#/properties/specversion"
    },
    "type": {
      "const": "com.mbta.ocs.raw_message",
      "$ref": "cloudevents.json#/properties/type"
    },
    "time": {
      "$ref": "cloudevents.json#/properties/time"
    },
    "partitionkey": {
      "type": "string",
      "minLength": 1,
      "description": "Key used to balance messages across multiple shards"
    },
    "data": {
      "description": "The event payload.",
      "$ref": "#/$defs/datadef"
    }
  },
  "required": [
    "id",
    "source",
    "specversion",
    "type",
    "data",
    "time",
    "partitionkey"
  ],
  "$defs": {
    "datadef": {
      "type": "object",
      "required": ["raw"],
      "properties": {
        "raw": {
          "description": "Raw OCS string, without the trailing record flag.",
          "type": "string",
          "minLength": 1,
          "examples": [
            "791612,RGPS,08:51:54,G,U15-141-626,3639,42.335725,71.145005,0.00,75.94"
          ]
        }
      }
    }
  }
}

=== mbta/schemas/examples/com.mbta.ocs.raw_message/RGPS.json
{
  "data": {
    "raw": "791612,RGPS,08:51:54,G,U15-141-626,3639,42.335725,71.145005,0.00,75.94"
  },
  "id": "prLSlfYXlQ8Nmsa8gyVi6PPZUmA=",
  "partitionkey": "{10.0.0.28:8081 -> 10.0.0.2:65473}",
  "source": "ctd.mbta.com/trike-1234",
  "specversion": "1.0",
  "time": "2023-01-29T13:51:54.990000Z",
  "type": "com.mbta.ocs.raw_message"
}
