=== mbta/schemas/schemas/com.mbta.ctd.glides.trips_updated.v1.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/mbta/schemas/blob/main/schemas/com.mbta.ctd.glides.trips_updated.v1.json",
  "description": "Trips Updated",
  "type": "object",
  "properties": {
    "type": { "const": "com.mbta.ctd.glides.trips_updated.v1" },
    "specversion": { "const": "1.0" },
    "source": { "$ref": "glides-events.json#/properties/source" },
    "id": { "$ref": "glides-events.json#/properties/id" },
    "time": { "$ref": "glides-events.json#/$defs/timestamp" },
    "data": {
      "type": "object",
      "properties": {
        "metadata": { "$ref": "glides-events.json#/$defs/metadata" },
        "tripUpdates": {
          "type": "array",
          "items": {
            "anyOf": [
              { "$ref": "#/$defs/trip_updated" },
              { "$ref": "#/$defs/trip_added" }
            ]
          }
        }
      },
      "required": ["metadata", "tripUpdates"]
    }
  },
  "required": ["type", "specversion", "source", "id", "time", "data"],
  "$defs": {
    "car": {
      "type": "object",
      "properties": {
        "label": {
          "oneOf": [{ "const": "none" }, { "type": "string", "minLength": 1 }]
        },
        "operator": {
          "oneOf": [
            { "const": "none" },
            { "const": "unset" },
            { "$ref": "glides-events.json#/$defs/operator" }
          ]
        }
      }
    },
    "dropped_reason": {
      "type": "object",
      "properties": {
        "reason": { "type": "string" }
      },
      "required": ["reason"]
    },
    "scheduled": {
      "type": "object",
      "properties": {
        "scheduledCars": {
          "type": "array",
          "minItems": 1,
          "maxItems": 2,
          "items": { "$ref": "#/$defs/scheduled_car" }
        }
      },
      "required": ["scheduledCars"]
    },
    "scheduled_car": {
      "type": "object",
      "properties": {
        "run": { "type": "string", "minLength": 1, "pattern": "^[1-9][0-9]*$" },
        "operator": { "$ref": "glides-events.json#/$defs/operator" }
      }
    },
    "service_date": {
      "type": "string",
      "minLength": 1,
      "$comment": "The date of service, which may not match the calendar date after midnight. RFC3339",
      "format": "date",
      "pattern": "^[0-9]{4}-[01][0-9]-[0-3][0-9]$",
      "examples": ["2023-12-31"]
    },
    "time": {
      "type": "string",
      "pattern": "^[012][0-9]:[0-5][0-9]:[0-6][0-9]$",
      "$comment": "HH:MM:SS, measured from 12hr before noon",
      "examples": ["04:30:00", "25:35:00"]
    },
    "trip_added": {
      "type": "object",
      "allOf": [
        { "$ref": "#/$defs/trip_updated" },
        {
          "properties": {
            "previousTripKey": { "$ref": "#/$defs/trip_key" },
            "type": { "const": "added" },
            "tripKey": {
              "$comment": "must use the added form of trip_key",
              "type": "object",
              "properties": { "glidesId": true },
              "required": ["glidesId"]
            }
          }
        },
        {
          "anyOf": [
            {
              "properties": { "startLocation": true },
              "required": ["startLocation"]
            },
            {
              "properties": { "endLocation": true },
              "required": ["endLocation"]
            }
          ]
        },
        {
          "anyOf": [
            { "properties": { "startTime": true }, "required": ["startTime"] },
            { "properties": { "endTime": true }, "required": ["endTime"] },
            {
              "properties": { "previousTripKey": true },
              "required": ["previousTripKey"]
            }
          ]
        }
      ]
    },
    "trip_key": {
      "type": "object",
      "properties": {
        "serviceDate": { "$ref": "#/$defs/service_date" }
      },
      "required": ["serviceDate"],
      "oneOf": [
        {
          "$comment": "added trip",
          "properties": {
            "glidesId": { "type": "string", "minLength": 1 }
          },
          "required": ["glidesId"]
        },
        {
          "$comment": "scheduled trip",
          "properties": {
            "startLocation": { "$ref": "glides-events.json#/$defs/location" },
            "endLocation": { "$ref": "glides-events.json#/$defs/location" },
            "startTime": { "$ref": "#/$defs/time" },
            "endTime": { "$ref": "#/$defs/time" }
          },
          "required": ["startLocation", "endLocation", "startTime", "endTime"]
        }
      ]
    },
    "trip_updated": {
      "type": "object",
      "properties": {
        "type": {
          "oneOf": [{ "const": "updated" }, { "const": "added" }]
        },
        "tripKey": { "$ref": "#/$defs/trip_key" },
        "comment": { "type": "string" },
        "startLocation": {
          "oneOf": [
            { "$ref": "glides-events.json#/$defs/location" },
            { "const": "unset" }
          ]
        },
        "endLocation": {
          "oneOf": [
            { "$ref": "glides-events.json#/$defs/location" },
            { "const": "unset" }
          ]
        },
        "startTime": {
          "oneOf": [{ "$ref": "#/$defs/time" }, { "const": "unset" }]
        },
        "endTime": {
          "oneOf": [{ "$ref": "#/$defs/time" }, { "const": "unset" }]
        },
        "cars": {
          "type": "array",
          "minItems": 1,
          "maxItems": 2,
          "items": { "$ref": "#/$defs/car" }
        },
        "dropped": {
          "oneOf": [{ "$ref": "#/$defs/dropped_reason" }, { "const": false }]
        },
        "scheduled": {
          "oneOf": [{ "$ref": "#/$defs/scheduled" }, { "const": null }]
        }
      },
      "required": ["type", "tripKey", "scheduled"]
    }
  }
}

=== mbta/schemas/examples/glides-events/trips_updated.v1.delay.json
{
  "type": "com.mbta.ctd.glides.trips_updated.v1",
  "specversion": "1.0",
  "source": "glides.mbta.com",
  "id": "19fdb184-7dd6-4664-8472-04bd6177ec44",
  "time": "2023-01-23T01:25:00-05:00",
  "data": {
    "metadata": {
      "inputType": "edit-trip"
    },
    "tripUpdates": [
      {
        "type": "updated",
        "tripKey": {
          "serviceDate": "2023-01-22",
          "startLocation": { "gtfsId": "place-matt" },
          "endLocation": { "gtfsId": "place-ashmt" },
          "startTime": "25:30:00",
          "endTime": "25:38:00"
        },
        "startTime": "25:45:00",
        "scheduled": {
          "scheduledCars": [{}]
        }
      }
    ]
  }
}

=== mbta/schemas/examples/glides-events/trips_updated.v1.publish_schedule.json
{
  "type": "com.mbta.ctd.glides.trips_updated.v1",
  "specversion": "1.0",
  "source": "glides.mbta.com",
  "id": "19fdb184-7dd6-4664-8472-04bd6177ec44",
  "time": "2024-11-21T17:00:00-05:00",
  "data": {
    "metadata": {
      "inputType": "publish-schedule"
    },
    "tripUpdates": [
      {
        "type": "updated",
        "tripKey": {
          "serviceDate": "2024-11-21",
          "tripId": "64085858",
          "startLocation": { "gtfsId": "place-matt" },
          "endLocation": { "gtfsId": "place-ashmt" },
          "startTime": "10:00:00",
          "endTime": "10:10:00"
        },
        "scheduled": {
          "scheduledCars": [
            {
              "run": "500",
              "operator": { "badgeNumber": "1234" }
            }
          ]
        }
      },
      {
        "type": "updated",
        "tripKey": {
          "serviceDate": "2024-11-21",
          "tripId": "64085858",
          "startLocation": { "gtfsId": "place-ashmt" },
          "endLocation": { "gtfsId": "place-matt" },
          "startTime": "10:11:00",
          "endTime": "10:21:00"
        },
        "scheduled": {
          "scheduledCars": [
            {
              "run": "500",
              "operator": { "badgeNumber": "1234" }
            }
          ]
        }
      }
    ]
  }
}

=== mbta/schemas/examples/glides-events/trips_updated.v1.dropped_and_headway.json
[
  {
    "type": "com.mbta.ctd.glides.trips_updated.v1",
    "specversion": "1.0",
    "source": "glides.mbta.com",
    "id": "19fdb184-7dd6-4664-8472-04bd6177ec44",
    "time": "2023-01-20T09:30:00-05:00",
    "data": {
      "metadata": {
        "inputType": "dropped-trip"
      },
      "tripUpdates": [
        {
          "type": "updated",
          "tripKey": {
            "serviceDate": "2022-01-20",
            "startLocation": { "gtfsId": "place-lake" },
            "endLocation": { "gtfsId": "place-gover" },
            "startTime": "10:05:00",
            "endTime": "10:52:00"
          },
          "dropped": { "reason": "staffing" },
          "scheduled": { "scheduledCars": [{}] }
        },
        {
          "type": "updated",
          "tripKey": {
            "serviceDate": "2022-01-20",
            "startLocation": { "gtfsId": "place-gover" },
            "endLocation": { "gtfsId": "place-lake" },
            "startTime": "10:55:00",
            "endTime": "10:42:00"
          },
          "dropped": { "reason": "staffing" },
          "scheduled": { "scheduledCars": [{}] }
        }
      ]
    }
  },
  {
    "type": "com.mbta.ctd.glides.trips_updated.v1",
    "specversion": "1.0",
    "source": "glides.mbta.com",
    "id": "19fdb184-7dd6-4664-8472-04bd6177ec44",
    "time": "2023-01-20T09:30:00-05:00",
    "data": {
      "metadata": {
        "inputType": "manage-headways"
      },
      "tripUpdates": [
        {
          "type": "updated",
          "tripKey": {
            "serviceDate": "2022-01-20",
            "startLocation": { "gtfsId": "place-lake" },
            "endLocation": { "gtfsId": "place-gover" },
            "startTime": "09:55:00",
            "endTime": "10:42:00"
          },
          "startTime": "9:56:00",
          "scheduled": { "scheduledCars": [{}] }
        },
        {
          "type": "updated",
          "tripKey": {
            "serviceDate": "2022-01-20",
            "startLocation": { "gtfsId": "place-lake" },
            "endLocation": { "gtfsId": "place-gover" },
            "startTime": "10:00:00",
            "endTime": "10:47:00"
          },
          "startTime": "10:02:00",
          "scheduled": { "scheduledCars": [{}] }
        },
        {
          "type": "updated",
          "tripKey": {
            "serviceDate": "2022-01-20",
            "startLocation": { "gtfsId": "place-lake" },
            "endLocation": { "gtfsId": "place-gover" },
            "startTime": "10:10:00",
            "endTime": "10:57:00"
          },
          "startTime": "10:08:00",
          "scheduled": { "scheduledCars": [{}] }
        }
      ]
    }
  }
]

=== mbta/schemas/examples/glides-events/trips_updated.v1.split.json
[
  {
    "type": "com.mbta.ctd.glides.trips_updated.v1",
    "specversion": "1.0",
    "source": "glides.mbta.com",
    "id": "19fdb184-7dd6-4664-8472-04bd6177ec44",
    "time": "2023-01-20T09:30:00-05:00",
    "data": {
      "metadata": {
        "inputType": "dropped-trip"
      },
      "tripUpdates": [
        {
          "type": "updated",
          "tripKey": {
            "serviceDate": "2022-01-20",
            "tripId": "64101244",
            "startLocation": { "gtfsId": "place-lake" },
            "endLocation": { "gtfsId": "place-gover" },
            "startTime": "10:00:00",
            "endTime": "10:47:00"
          },
          "dropped": { "reason": "ran as single" },
          "scheduled": {
            "scheduledCars": [
              {
                "run": "506",
                "operator": { "badgeNumber": "678" }
              },
              {
                "run": "507",
                "operator": { "badgeNumber": "789" }
              }
            ]
          }
        }
      ]
    }
  },
  {
    "type": "com.mbta.ctd.glides.trips_updated.v1",
    "specversion": "1.0",
    "source": "glides.mbta.com",
    "id": "19fdb184-7dd6-4664-8472-04bd6177ec44",
    "time": "2023-01-20T09:30:00-05:00",
    "data": {
      "metadata": {
        "inputType": "edit-trip"
      },
      "tripUpdates": [
        {
          "type": "updated",
          "tripKey": {
            "serviceDate": "2022-01-20",
            "tripId": "64101243",
            "startLocation": { "gtfsId": "place-lake" },
            "endLocation": { "gtfsId": "place-gover" },
            "startTime": "09:55:00",
            "endTime": "10:42:00"
          },
          "comment": "single",
          "cars": [
            {
              "label": "3800",
              "operator": { "badgeNumber": "456" }
            }
          ],
          "scheduled": {
            "scheduledCars": [
              {
                "run": "504",
                "operator": { "badgeNumber": "456" }
              },
              {
                "run": "505",
                "operator": { "badgeNumber": "567" }
              }
            ]
          }
        }
      ]
    }
  },
  {
    "type": "com.mbta.ctd.glides.trips_updated.v1",
    "specversion": "1.0",
    "source": "glides.mbta.com",
    "id": "19fdb184-7dd6-4664-8472-04bd6177ec44",
    "time": "2023-01-20T09:30:00-05:00",
    "data": {
      "metadata": {
        "inputType": "add-trip"
      },
      "tripUpdates": [
        {
          "type": "added",
          "tripKey": {
            "serviceDate": "2022-01-20",
            "glidesId": "ADDED-1"
          },
          "startLocation": { "gtfsId": "place-lake" },
          "startTime": "10:00:00",
          "cars": [
            {
              "label": "3850",
              "operator": { "badgeNumber": "567" }
            }
          ],
          "scheduled": null
        },
        {
          "type": "added",
          "tripKey": {
            "serviceDate": "2022-01-20",
            "glidesId": "ADDED-2"
          },
          "endLocation": { "gtfsId": "place-lake" },
          "previousTripKey": {
            "serviceDate": "2022-01-20",
            "glidesId": "ADDED-1"
          },
          "cars": [
            {
              "label": "3850",
              "operator": { "badgeNumber": "567" }
            }
          ],
          "scheduled": null
        }
      ]
    }
  }
]
