=== mbta/schemas/schemas/com.mbta.ocs.tmov_light_rail.v1.json
{
  "$id": "https://github.com/mbta/schemas/blob/main/schemas/com.mbta.ocs.tmov_light_rail.v1.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "description": "OCS message about movement of light rail vehicles",
  "type": "object",
  "properties": {
    "id": {
      "$ref": "cloudevents.json#/properties/id",
      "examples": ["prLSlfYXlQ8Nmsa8gyVi6PPZUmA="]
    },
    "source": {
      "$ref": "cloudevents.json#/properties/source",
      "examples": ["mbta.com/trike-12345"]
    },
    "specversion": {
      "const": "1.0",
      "$ref": "cloudevents.json#/properties/specversion"
    },
    "type": {
      "const": "com.mbta.ocs.tmov_light_rail.v1",
      "$ref": "cloudevents.json#/properties/type"
    },
    "time": {
      "$ref": "cloudevents.json#/properties/time"
    },
    "partitionkey": {
      "type": "string",
      "minLength": 1,
      "description": "Key used to balance messages across multiple shards"
    },
    "data": {
      "description": "The event payload.",
      "$ref": "#/$defs/datadef"
    }
  },
  "required": [
    "id",
    "source",
    "specversion",
    "type",
    "data",
    "time",
    "partitionkey"
  ],
  "$defs": {
    "datadef": {
      "type": "object",
      "allOf": [
        { "$ref": "ocs-events-common.json#/$defs/tmovCommonBase" },
        { "$ref": "ocs-events-common.json#/$defs/tmovCommonAdditional" },
        {
          "required": [
            "routeNumber",
            "lastAvi",
            "dataSource",
            "consist",
            "speed",
            "heading"
          ],
          "properties": {
            "routeNumber": {
              "description": "",
              "type": "string"
            },
            "lastAvi": {
              "description": "",
              "type": "string"
            },
            "dataSource": {
              "description": "The comm type from which positional data was obtained. `avi` indicates information was obtained from an AVI read via a wayside device. `nvl` (\"non-vital logic\") indicates information was obtained from a track circuit. `gps` indicates information was obtained from a GPS",
              "$comment": "TODO: (1) Is it safe for this to be an enum? (2) Is it best to drop the `ci` suffix as RTR does?",
              "type": "string",
              "enum": ["avi", "nvl", "gps"]
            },
            "consist": {
              "description": "Full consist, ie car numbers of this vehicle",
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "speed": {
              "description": "Speed of vehicle, if dataSource is gps",
              "$comment": "TODO: RTR uses an explicit 'unreported' value here. Should we just be optional / nullable?",
              "oneOf": [
                {
                  "type": "number"
                },
                {
                  "const": "unreported"
                }
              ]
            },
            "heading": {
              "description": "Direction the vehicle is pointing, measured in degrees from Magnetic North. Only provided with GPS data source.",
              "$comment": "TODO: RTR uses an explicit 'unreported' value here. Should we just be optional / nullable?",
              "type": ["number", "null"]
            },
            "orientation": {
              "description": "Whether the 'rear' or 'front' of each train is facing forward for each train in the consist. B means backward, A means forward. Only provided with AVI data source.",
              "type": ["string", "null"]
            }
          }
        }
      ]
    }
  }
}

=== mbta/schemas/examples/com.mbta.ocs.tmov_light_rail.v1/green-line-avi-example.json
{
  "id": "prLSlfYXlQ8Nmsa8gyVi6PPZUmA=",
  "partitionkey": "{10.0.0.28:8081 -> 10.0.0.2:65473}",
  "source": "ctd.mbta.com/trike-1234",
  "specversion": "1.0",
  "time": "2023-01-29T13:51:54.990000Z",
  "type": "com.mbta.ocs.tmov_light_rail.v1",
  "data": {
    "counter": 70877,
    "timestamp": "2025-06-06T13:17:37.632951-04:00",
    "transitLine": "G",
    "trainUid": "10001",
    "latitude": 42.39788390892353,
    "longitude": -71.10940113113155,
    "trainTag": "normal",
    "leadCar": "3820",
    "dispatchTags": [ "restricted", "isolated" ],
    "routeNumber": "855",
    "lastAvi": "6",
    "dataSource": "avi",
    "consist": [ "3820", "3827" ],
    "speed": "unreported",
    "heading": null,
    "orientation": "BA"
  }
}

=== mbta/schemas/examples/com.mbta.ocs.tmov_light_rail.v1/green-line-nvl-example.json
{
  "id": "prLSlfYXlQ8Nmsa8gyVi6PPZUmA=",
  "partitionkey": "{10.0.0.28:8081 -> 10.0.0.2:65473}",
  "source": "ctd.mbta.com/trike-1234",
  "specversion": "1.0",
  "time": "2023-01-29T13:51:54.990000Z",
  "type": "com.mbta.ocs.tmov_light_rail.v1",
  "data": {
    "counter": 70877,
    "timestamp": "2025-06-06T13:17:37.632951-04:00",
    "transitLine": "G",
    "trainUid": "10001",
    "latitude": 42.39788390892353,
    "longitude": -71.10940113113155,
    "trainTag": "normal",
    "leadCar": "3820",
    "dispatchTags": [ "K", "D" ],
    "routeNumber": "886",
    "lastAvi": "11",
    "dataSource": "nvl",
    "consist": [ "3820", "3827" ],
    "speed": 35.79,
    "heading": null,
    "orientation": null
  }
}
