=== mbta/schemas/schemas/com.mbta.ocs.tmov_heavy_rail.v1.json
{
  "$id": "https://github.com/mbta/schemas/blob/main/schemas/com.mbta.ocs.tmov_heavy_rail.v1.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "description": "OCS message about movement of heavy rail vehicles",
  "type": "object",
  "properties": {
    "id": {
      "$ref": "cloudevents.json#/properties/id",
      "examples": ["prLSlfYXlQ8Nmsa8gyVi6PPZUmA="]
    },
    "source": {
      "$ref": "cloudevents.json#/properties/source",
      "examples": ["mbta.com/trike-12345"]
    },
    "specversion": {
      "const": "1.0",
      "$ref": "cloudevents.json#/properties/specversion"
    },
    "type": {
      "const": "com.mbta.ocs.tmov_heavy_rail.v1",
      "$ref": "cloudevents.json#/properties/type"
    },
    "time": {
      "$ref": "cloudevents.json#/properties/time"
    },
    "partitionkey": {
      "type": "string",
      "minLength": 1,
      "description": "Key used to balance messages across multiple shards"
    },
    "data": {
      "description": "The event payload.",
      "$ref": "#/$defs/datadef"
    }
  },
  "required": [
    "id",
    "source",
    "specversion",
    "type",
    "data",
    "time",
    "partitionkey"
  ],
  "$defs": {
    "datadef": {
      "type": "object",
      "allOf": [
        { "$ref": "ocs-events-common.json#/$defs/tmovCommonBase" },
        { "$ref": "ocs-events-common.json#/$defs/tmovCommonAdditional" },
        {
          "required": ["ashmont", "tripUid", "expressLocation"],
          "properties": {
            "ashmont": {
              "description": "Set to true if train is on the Ashmont Route (ie, if destination of trip is Ashmont or Codman Yard",
              "type": "boolean"
            },
            "tripUid": {
              "description": "Unique ID for the scheduled trip associated with this train. Only unique within a transit line.",
              "type": "string"
            },
            "expressLocation": {
              "description": "Express to station name",
              "$comment": "TODO: Clarify this value. Is this used? Having trouble finding an example in splunk of a non-empty value",
              "type": "string"
            }
          }
        }
      ]
    }
  }
}

=== mbta/schemas/examples/com.mbta.ocs.tmov_heavy_rail.v1/red-line-example.json
{
  "id": "prLSlfYXlQ8Nmsa8gyVi6PPZUmA=",
  "partitionkey": "{10.0.0.28:8081 -> 10.0.0.2:65473}",
  "source": "ctd.mbta.com/trike-1234",
  "specversion": "1.0",
  "time": "2023-01-29T13:51:54.990000Z",
  "type": "com.mbta.ocs.tmov_heavy_rail.v1",
  "data": {
    "counter": 70877,
    "timestamp": "2025-06-06T13:17:37.632951-04:00",
    "transitLine": "R",
    "trainUid": "54838C33",
    "latitude": 42.374346,
    "longitude": -71.030170,
    "trainTag": "normal",
    "leadCar": "2507",
    "leadCarDisplay": "1507", 
    "dispatchTags": [ "K", "D" ],
    "ashmont": false,
    "tripUid": "981498C2",
    "expressLocation": ""
  }
}

=== mbta/schemas/examples/com.mbta.ocs.tmov_heavy_rail.v1/blue-line-example.json
{
  "id": "prLSlfYXlQ8Nmsa8gyVi6PPZUmA=",
  "partitionkey": "{10.0.0.28:8081 -> 10.0.0.2:65473}",
  "source": "ctd.mbta.com/trike-1234",
  "specversion": "1.0",
  "time": "2023-01-29T13:51:54.990000Z",
  "type": "com.mbta.ocs.tmov_heavy_rail.v1",
  "data": {
    "counter": 70877,
    "timestamp": "2025-06-06T13:17:37.632951-04:00",
    "transitLine": "B",
    "trainUid": "548386EB",
    "latitude": 42.374346,
    "longitude": -71.030170,
    "trainTag": "normal",
    "leadCar": "0760",
    "dispatchTags": [ "restricted", "isolated" ],
    "ashmont": false,
    "tripUid": "98BB4163",
    "expressLocation": ""
  }
}
