=== mbta/schemas/schemas/com.mbta.ocs.tsch_new.v1.json
{
  "$id": "https://github.com/mbta/schemas/blob/main/schemas/com.mbta.ocs.tsch_new.v1.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "description": "OCS TSCH message to indicate new trip info - new trip either loaded from the quarterly pick files (Hastus) or added by dispatcher or auto generated by the system",
  "type": "object",
  "properties": {
    "id": {
      "$ref": "cloudevents.json#/properties/id",
      "examples": ["prLSlfYXlQ8Nmsa8gyVi6PPZUmA="]
    },
    "source": {
      "$ref": "cloudevents.json#/properties/source",
      "examples": ["mbta.com/trike-12345"]
    },
    "specversion": {
      "const": "1.0",
      "$ref": "cloudevents.json#/properties/specversion"
    },
    "type": {
      "const": "com.mbta.ocs.tsch_new.v1",
      "$ref": "cloudevents.json#/properties/type"
    },
    "time": {
      "$ref": "cloudevents.json#/properties/time"
    },
    "partitionkey": {
      "type": "string",
      "minLength": 1,
      "description": "Key used to balance messages across multiple shards"
    },
    "data": {
      "description": "The event payload.",
      "$ref": "#/$defs/datadef"
    }
  },
  "required": [
    "id",
    "source",
    "specversion",
    "type",
    "data",
    "time",
    "partitionkey"
  ],
  "$defs": {
    "datadef": {
      "type": "object",
      "allOf": [
        { "$ref": "ocs-events-common.json#/$defs/tschCommonBase" },
        {
          "required": [
            "tripUid",
            "addType",
            "tripType",
            "scheduledDepartureTime",
            "scheduledArrivalTime",
            "ocsRouteId",
            "originStation",
            "destinationStation",
            "previousTripUid",
            "nextTripUid"
          ],
          "properties": {
            "tripUid": {
              "description": "Trip UID - only unique within a transit line.",
              "type": "string"
            },
            "addType": {
              "description": "Possible values: S -- Schedule Loaded (nightly right after 2am or if dispatcher manually selects a schedule), around 1,500 messages will be delivered at once. A -- Dispatcher or auto system Add",
              "$comment": "TODO: Enum-ify this?",
              "type": "string"
            },
            "tripType": {
              "description": "Single character indicating trip type. See OCS raw for possible values.",
              "$comment": "TODO: Enum-ify this? Put the (very long) description in-line?",
              "type": "string"
            },
            "scheduledDepartureTime": {
              "description": "Scheduled departure - RFC3339 timestamp",
              "$ref": "ocs-events-common.json#/$defs/timestamp"
            },
            "scheduledArrivalTime": {
              "description": "Scheduled arrival - RFC3339 timestamp",
              "$ref": "ocs-events-common.json#/$defs/timestamp"
            },
            "ocsRouteId": {
              "description": "5 characters representing the route",
              "type": ["string", "null"]
            },
            "originStation": {
              "description": "Origin station name",
              "type": ["string", "null"]
            },
            "destinationStation": {
              "description": "Destination station name",
              "type": ["string", "null"]
            },
            "previousTripUid": {
              "description": "Previous trip UID - only unique within a transit line.",
              "type": ["string", "null"]
            },
            "nextTripUid": {
              "description": "Next trip UID - only unique within a transit line.",
              "type": ["string", "null"]
            }
          }
        }
      ]
    }
  }
}

=== mbta/schemas/examples/com.mbta.ocs.tsch_new.v1/scheduled-trip-example.json
{
  "id": "prLSlfYXlQ8Nmsa8gyVi6PPZUmA=",
  "partitionkey": "{10.0.0.28:8081 -> 10.0.0.2:65473}",
  "source": "ctd.mbta.com/trike-1234",
  "specversion": "1.0",
  "time": "2023-01-29T13:51:54.990000Z",
  "type": "com.mbta.ocs.tsch_new.v1",
  "data": {
    "counter": 70877,
    "timestamp": "2025-06-02T18:45:43.958582-04:00",
    "transitLine": "R",
    "tripUid": "981494FC",
    "addType": "S",
    "tripType": "R",
    "scheduledDepartureTime": "2025-06-08T19:45:00-04:00",
    "scheduledArrivalTime": "2025-06-08T20:33:00-04:00",
    "ocsRouteId": "N933_",
    "originStation": "BRAINTREE",
    "destinationStation": "ALEWIFE",
    "previousTripUid": "981494FB",
    "nextTripUid": "981494FD"
  }
}

=== mbta/schemas/examples/com.mbta.ocs.tsch_new.v1/added-trip-example.json
{
  "id": "prLSlfYXlQ8Nmsa8gyVi6PPZUmA=",
  "partitionkey": "{10.0.0.28:8081 -> 10.0.0.2:65473}",
  "source": "ctd.mbta.com/trike-1234",
  "specversion": "1.0",
  "time": "2023-01-29T13:51:54.990000Z",
  "type": "com.mbta.ocs.tsch_new.v1",
  "data": {
    "counter": 70877,
    "timestamp": "2025-06-02T18:45:43.958582-04:00",
    "transitLine": "B",
    "tripUid": "98BB3A47",
    "addType": "A",
    "tripType": "A",
    "scheduledDepartureTime": "2025-06-02T18:45:00-04:00",
    "scheduledArrivalTime": "2025-06-02T19:00:00-04:00",
    "ocsRouteId": "rad",
    "originStation": "ORIENT HEIGHTS",
    "destinationStation": "BOWDOIN",
    "previousTripUid": null,
    "nextTripUid": null
  }
}
