=== mbta/schemas/schemas/com.mbta.ocs.tsch_lnk.v1.json
{
  "$id": "https://github.com/mbta/schemas/blob/main/schemas/com.mbta.ocs.tsch_lnk.v1.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "description": "OCS TSCH message to update a train's previous or next trip ID",
  "type": "object",
  "properties": {
    "id": {
      "$ref": "cloudevents.json#/properties/id",
      "examples": ["prLSlfYXlQ8Nmsa8gyVi6PPZUmA="]
    },
    "source": {
      "$ref": "cloudevents.json#/properties/source",
      "examples": ["mbta.com/trike-12345"]
    },
    "specversion": {
      "const": "1.0",
      "$ref": "cloudevents.json#/properties/specversion"
    },
    "type": {
      "const": "com.mbta.ocs.tsch_lnk.v1",
      "$ref": "cloudevents.json#/properties/type"
    },
    "time": {
      "$ref": "cloudevents.json#/properties/time"
    },
    "partitionkey": {
      "type": "string",
      "minLength": 1,
      "description": "Key used to balance messages across multiple shards"
    },
    "data": {
      "description": "The event payload.",
      "$ref": "#/$defs/datadef"
    }
  },
  "required": [
    "id",
    "source",
    "specversion",
    "type",
    "data",
    "time",
    "partitionkey"
  ],
  "$defs": {
    "datadef": {
      "type": "object",
      "allOf": [
        { "$ref": "ocs-events-common.json#/$defs/tschCommonBase" },
        {
          "required": ["tripUid", "previousTripUid", "nextTripUid"],
          "properties": {
            "tripUid": {
              "description": "Trip UID - only unique within a transit line.",
              "type": "string"
            },
            "previousTripUid": {
              "description": "Trip UID - only unique within a transit line.",
              "type": ["string", "null"]
            },
            "nextTripUid": {
              "description": "Trip UID - only unique within a transit line.",
              "type": ["string", "null"]
            }
          }
        }
      ]
    }
  }
}

=== mbta/schemas/examples/com.mbta.ocs.tsch_lnk.v1/update-next-trip-example.json
{
  "id": "prLSlfYXlQ8Nmsa8gyVi6PPZUmA=",
  "partitionkey": "{10.0.0.28:8081 -> 10.0.0.2:65473}",
  "source": "ctd.mbta.com/trike-1234",
  "specversion": "1.0",
  "time": "2023-01-29T13:51:54.990000Z",
  "type": "com.mbta.ocs.tsch_lnk.v1",
  "data": {
    "counter": 70877,
    "timestamp": "2025-06-06T13:17:37.632951-04:00",
    "transitLine": "B",
    "tripUid": "98149418",
    "previousTripUid": null,
    "nextTripUid": "98149419"
  }
}
