=== mbta/schemas/schemas/glides-events-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/mbta/schemas/blob/main/schemas/glides-events-schema.json",
  "title": "Glides Events",
  "description": "Kinesis events emitted by Glides",
  "type": "object",
  "properties": {
    "type": {
      "type": "string",
      "description": "name of the event",
      "$comment": "enforced to be a valid event name by the oneOf, below"
    },
    "specversion": {
      "type": "string",
      "const": "1.0"
    },
    "source": {
      "type": "string",
      "const": "glides.mbta.com"
    },
    "id": {
      "type": "string",
      "minLength": 1,
      "examples": ["19fdb184-7dd6-4664-8472-04bd6177ec44"]
    },
    "time": {
      "type": "string",
      "examples": ["2023-01-20T09:30:00-05:00"]
    },
    "data": {
      "type": "object",
      "$comment": "validated by the oneOf, below"
    }
  },
  "required": ["type", "specversion", "source", "id", "time", "data"],
  "oneOf": [
    {
      "properties": {
        "type": { "const": "com.mbta.ctd.glides.editors_changed.v1" },
        "data": { "$ref": "#/$defs/editors_changed_v1" }
      }
    },
    {
      "properties": {
        "type": { "const": "com.mbta.ctd.glides.operator_signed_in.v1" },
        "data": { "$ref": "#/$defs/operator_signed_in_v1" }
      }
    },
    {
      "properties": {
        "type": { "const": "com.mbta.ctd.glides.trips_updated.v1" },
        "data": { "$ref": "#/$defs/trips_updated_v1" }
      }
    }
  ],
  "$defs": {
    "editors_changed_v1": {},
    "operator_signed_in_v1": {},
    "trips_updated_v1": {}
  }
}

=== mbta/schemas/examples/glides-events/editors_changed.v1.take_over.json
{
  "type": "com.mbta.ctd.glides.editors_changed.v1",
  "specversion": "1.0",
  "source": "glides.mbta.com",
  "id": "19fdb184-7dd6-4664-8472-04bd6177ec44",
  "time": "2023-01-20T09:30:00-05:00",
  "data": {
    "metadata": {
      "author": {
        "emailAddress": "ainspector@example.com",
        "badgeNumber": "123"
      },
      "inputTimestamp": "2023-01-20T09:29:59-05:00",
      "inputType": "take-over-editing",
      "location": { "todsId": "lakst" }
    },
    "changes": [
      {
        "type": "stop",
        "location": { "todsId": "lakst" },
        "editor": {
          "emailAddress": "binspector@example.com",
          "badgeNumber": "456"
        }
      },
      {
        "type": "start",
        "location": { "todsId": "lakst" },
        "editor": {
          "emailAddress": "ainspector@example.com",
          "badgeNumber": "123"
        }
      }
    ]
  }
}

=== mbta/schemas/examples/glides-events-schema/glides-examples.json
[
  {
    "type": "com.mbta.ctd.glides.editors_changed.v1",
    "specversion": "1.0",
    "source": "glides.mbta.com",
    "id": "19fdb184-7dd6-4664-8472-04bd6177ec44",
    "time": "2023-01-20T09:30:00-05:00",
    "data": {
      "metadata": {
        "author": {
          "emailAddress": "ainspector@example.com",
          "badgeNumber": "123"
        },
        "inputTimestamp": "2023-01-20T09:29:59-05:00",
        "inputType": "take-over-editing",
        "location": { "gtfsId": "place-lake" }
      },
      "changes": [
        {
          "type": "stop",
          "location": { "gtfsId": "place-lake" },
          "editor": {
            "emailAddress": "binspector@example.com",
            "badgeNumber": "456"
          }
        },
        {
          "type": "start",
          "location": { "gtfsId": "place-lake" },
          "editor": {
            "emailAddress": "ainspector@example.com",
            "badgeNumber": "123"
          }
        }
      ]
    }
  },
  {
    "type": "com.mbta.ctd.glides.operator_signed_in.v1",
    "specversion": "1.0",
    "source": "glides.mbta.com",
    "id": "19fdb184-7dd6-4664-8472-04bd6177ec44",
    "time": "2023-01-20T09:30:00-05:00",
    "data": {
      "metadata": {},
      "operator": { "badgeNumber": "789" },
      "signedInAt": "2023-01-20T09:45:00-05:00",
      "signature": { "type": "tap" }
    }
  },
  {
    "type": "com.mbta.ctd.glides.trips_updated.v1",
    "specversion": "1.0",
    "source": "glides.mbta.com",
    "id": "19fdb184-7dd6-4664-8472-04bd6177ec44",
    "time": "2023-01-20T09:30:00-05:00",
    "data": {
      "metadata": {
        "inputType": "dropped-trip"
      },
      "tripUpdates": [
        {
          "type": "updated",
          "tripKey": {
            "serviceDate": "2022-01-20",
            "startLocation": { "gtfsId": "place-lake" },
            "endLocation": { "gtfsId": "place-gover" },
            "startTime": "10:05:00",
            "endTime": "10:52:00"
          },
          "dropped": { "reason": "staffing" },
          "scheduled": { "scheduledCars": [{}] }
        },
        {
          "type": "updated",
          "tripKey": {
            "serviceDate": "2022-01-20",
            "startLocation": { "gtfsId": "place-gover" },
            "endLocation": { "gtfsId": "place-lake" },
            "startTime": "10:55:00",
            "endTime": "10:42:00"
          },
          "dropped": { "reason": "staffing" },
          "scheduled": { "scheduledCars": [{}] }
        }
      ]
    }
  },
  {
    "type": "com.mbta.ctd.glides.trips_updated.v1",
    "specversion": "1.0",
    "source": "glides.mbta.com",
    "id": "19fdb184-7dd6-4664-8472-04bd6177ec44",
    "time": "2023-01-20T09:30:00-05:00",
    "data": {
      "metadata": {
        "inputType": "manage-headways"
      },
      "tripUpdates": [
        {
          "type": "updated",
          "tripKey": {
            "serviceDate": "2022-01-20",
            "startLocation": { "gtfsId": "place-lake" },
            "endLocation": { "gtfsId": "place-gover" },
            "startTime": "09:55:00",
            "endTime": "10:42:00"
          },
          "startTime": "9:56:00",
          "scheduled": { "scheduledCars": [{}] }
        },
        {
          "type": "updated",
          "tripKey": {
            "serviceDate": "2022-01-20",
            "startLocation": { "gtfsId": "place-lake" },
            "endLocation": { "gtfsId": "place-gover" },
            "startTime": "10:00:00",
            "endTime": "10:47:00"
          },
          "startTime": "10:02:00",
          "scheduled": { "scheduledCars": [{}] }
        },
        {
          "type": "updated",
          "tripKey": {
            "serviceDate": "2022-01-20",
            "startLocation": { "gtfsId": "place-lake" },
            "endLocation": { "gtfsId": "place-gover" },
            "startTime": "10:10:00",
            "endTime": "10:57:00"
          },
          "startTime": "10:08:00",
          "scheduled": { "scheduledCars": [{}] }
        }
      ]
    }
  },
  {
    "type": "com.mbta.ctd.glides.trips_updated.v1",
    "specversion": "1.0",
    "source": "glides.mbta.com",
    "id": "19fdb184-7dd6-4664-8472-04bd6177ec44",
    "time": "2023-01-20T09:30:00-05:00",
    "data": {
      "metadata": {
        "inputType": "dropped-trip"
      },
      "updatedTrips": [
        {
          "type": "updated",
          "tripKey": {
            "serviceDate": "2022-01-20",
            "startLocation": { "gtfsId": "place-lake" },
            "endLocation": { "gtfsId": "place-gover" },
            "startTime": "10:00:00",
            "endTime": "10:47:00"
          },
          "dropped": { "reason": "ran as single" },
          "scheduled": {
            "scheduledCars": [
              {
                "run": "506",
                "operator": { "badgeNumber": "678" }
              },
              {
                "run": "507",
                "operator": { "badgeNumber": "789" }
              }
            ]
          }
        }
      ]
    }
  },
  {
    "type": "com.mbta.ctd.glides.trips_updated.v1",
    "specversion": "1.0",
    "source": "glides.mbta.com",
    "id": "19fdb184-7dd6-4664-8472-04bd6177ec44",
    "time": "2023-01-20T09:30:00-05:00",
    "data": {
      "metadata": {
        "inputType": "edit-trip"
      },
      "updatedTrips": [
        {
          "type": "updated",
          "tripKey": {
            "serviceDate": "2022-01-20",
            "startLocation": { "gtfsId": "place-lake" },
            "endLocation": { "gtfsId": "place-gover" },
            "startTime": "09:55:00",
            "endTime": "10:42:00"
          },
          "comment": "single",
          "cars": [
            {
              "label": "3800",
              "operator": { "badgeNumber": "456" }
            }
          ],
          "scheduled": {
            "scheduledCars": [
              {
                "run": "504",
                "operator": { "badgeNumber": "456" }
              },
              {
                "run": "505",
                "operator": { "badgeNumber": "567" }
              }
            ]
          }
        }
      ]
    }
  },
  {
    "type": "com.mbta.ctd.glides.trips_updated.v1",
    "specversion": "1.0",
    "source": "glides.mbta.com",
    "id": "19fdb184-7dd6-4664-8472-04bd6177ec44",
    "time": "2023-01-20T09:30:00-05:00",
    "data": {
      "metadata": {
        "inputType": "add-trip"
      },
      "updatedTrips": [
        {
          "type": "added",
          "tripKey": {
            "serviceDate": "2022-01-20",
            "id": "ADDED-1"
          },
          "startLocation": { "gtfsId": "place-lake" },
          "startTime": "10:00:00",
          "nextTripKey": {
            "serviceDate": "2022-01-20",
            "id": "ADDED-2"
          },
          "cars": [
            {
              "label": "3850",
              "operator": { "badgeNumber": "567" }
            }
          ],
          "scheduled": null
        },
        {
          "type": "added",
          "tripKey": {
            "serviceDate": "2022-01-20",
            "id": "ADDED-2"
          },
          "endLocation": { "gtfsId": "place-lake" },
          "previousTripKey": {
            "serviceDate": "2022-01-20",
            "id": "ADDED-1"
          },
          "cars": [
            {
              "label": "3850",
              "operator": { "badgeNumber": "567" }
            }
          ],
          "scheduled": null
        }
      ]
    }
  },
  {
    "type": "com.mbta.ctd.glides.trips_updated.v1",
    "specversion": "1.0",
    "source": "glides.mbta.com",
    "id": "19fdb184-7dd6-4664-8472-04bd6177ec44",
    "time": "2023-01-23T01:25:00-05:00",
    "data": {
      "metadata": {
        "inputType": "edit-trip"
      },
      "updatedTrips": [
        {
          "type": "updated",
          "tripKey": {
            "serviceDate": "2023-01-22",
            "startLocation": { "gtfsId": "place-matt" },
            "endLocation": { "gtfsId": "place-ashmt" },
            "startTime": "25:30:00",
            "endTime": "25:38:00"
          },
          "location": { "gtfsId": "place-matt" },
          "startTime": "25:45:00"
        }
      ]
    }
  }
]

=== mbta/schemas/examples/glides-events/operator_signed_in.v1.json
{
  "type": "com.mbta.ctd.glides.operator_signed_in.v1",
  "specversion": "1.0",
  "source": "glides.mbta.com",
  "id": "19fdb184-7dd6-4664-8472-04bd6177ec44",
  "time": "2023-01-20T09:30:00-05:00",
  "data": {
    "metadata": {
      "author": {
        "emailAddress": "ainspector@example.com",
        "badgeNumber": "123"
      },
      "inputTimestamp": "2023-01-20T09:29:59-05:00",
      "inputType": "sign-in",
      "location": { "todsId": "lakst" }
    },
    "operator": { "badgeNumber": "789" },
    "signedInAt": "2023-01-20T09:45:00-05:00",
    "signature": { "type": "tap", "version": 1 }
  }
}
